title: Simulated Markets Project
description: Documentation for the Simulated Markets Project 
theme: just-the-docs

url: https://github.com/evanalbers/market-sim

aux_links:
  "Simulated Markets on GitHub":
    - "https://github.com/evanalbers/market-sim"